-- MySQL Script generated by MySQL Workbench
-- Thu Feb  9 17:01:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE TABLE IF NOT EXISTS `shopify`.`products` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `product_name` VARCHAR(255) NULL,
    `product_description` VARCHAR(255) NULL,
    `product_price` SMALLINT NULL,
    `product_stock` SMALLINT NULL,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    PRIMARY KEY (`id`))
ENGINE = InnoDB;
